#!/bin/bash

java -Xms256M -Xmx512M -classpath `find ../VASSAL-lib -name '*.jar' | tr '\n' ':'`classes:Vengine.jar -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel -Dswing.boldMetal=false -Dswing.aatext=true -Dsun.java2d.opengl=True VASSAL.launch.Main
