#!/bin/bash

java -Xms256M -Xmx512M -classpath ../VASSAL-lib/VASSAL.jar:../VASSAL-lib/docs.jar:../VASSAL-lib/cryptix32.jar:../VASSAL-lib/batik.jar:../VASSAL-lib/smack.jar:../VASSAL-lib/smackx.jar:../VASSAL-lib/smackx-debug.jar:classes:Vengine.jar -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel -Dswing.boldMetal=false -Dswing.aatext=true -Dsun.java2d.opengl=true org.vassalengine.Main
